package hibernate.entity;
// Generated 11 mar. 2019 12:57:36 by Hibernate Tools 4.3.1



/**
 * Canciones generated by hbm2java
 */
public class Canciones  implements java.io.Serializable {


     private String _1_nom;
     private String _2_genere;
     private String _3_data;

    public Canciones() {
    }

	
    public Canciones(String _1_nom) {
        this._1_nom = _1_nom;
    }
    public Canciones(String _1_nom, String _2_genere, String _3_data) {
       this._1_nom = _1_nom;
       this._2_genere = _2_genere;
       this._3_data = _3_data;
    }
   
    public String get_1_Nom() {
        return this._1_nom;
    }
    
    public void set_1_Nom(String _1_nom) {
        this._1_nom = _1_nom;
    }
    public String get_2_Genere() {
        return this._2_genere;
    }
    
    public void set_2_Genere(String _2_genere) {
        this._2_genere = _2_genere;
    }
    public String get_3_Data() {
        return this._3_data;
    }
    
    public void set_3_Data(String _3_data) {
        this._3_data = _3_data;
    }




}


